apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ngo-app
  name: ngo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngo-app
  template:
    metadata:
      labels:
        app: ngo-app
    spec:
    containers:
      - image: 277285677846.dkr.ecr.eu-west-2.amazonaws.com/capstone:latest
        name: ngo-app
        environment:
          - name: DB_HOST
            value: mongo-db
          - name: DB_PORT
            value: 27017 
          - name: DB_USER
            value: admin
          - name: DB_PASS
            value: password
          - name: DB_NAME
            value: admin 
        restart: unless-stopped
        ports:
        - containerPort: 8080
          name: ngo-app
  # volumes:
  #     - name: ngo-app-data
  #       emptyDir: {} 

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: ngo-app
  name: ngo-app
spec:  
  type: LoadBalancer
  ports:
  - name: "ngo-app-service"
    port: 80
    targetPort: 8080
  selector:
    app: ngo-app