apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
    containers:
      - name: webapp
        image: 277285677846.dkr.ecr.eu-west-2.amazonaws.com/capstone:latest
        ports:
        - containerPort: 8080
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: DB_USER
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: DB_PASS
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080