apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  labels:
    app: capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - name: capstone
          image: 123456789012.dkr.ecr.eu-west-1.amazonaws.com/capstone;latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080