apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-12
  labels:
    app: capstone-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-12
  template:
    metadata:
      labels:
        app: capstone-12
    spec:
      containers:
        - name: capstone-12
          image: 123456789012.dkr.ecr.eu-west-1.amazonaws.com/capstone-12:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080