apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app
spec:
  replicas: 3  # Adjust the number of replicas as per your requirement
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
    containers:
        - name: capstone
          image: your-docker-hub-username/capstone:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: mongo-db
            - name: DB_PORT
              value: "27017"
            - name: DB_USER
              value: admin
            - name: DB_PASS
              value: password
            - name: DB_NAME
              value: admin
        - name: mongo-db
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
            - name: MONGO_INITDB_DATABASE
              value: admin
            - name: MONGODB_URI
              value: mongodb://mongo-db:27017
