apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-db
  name: mongo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
      - image: mongo:latest
        name: mongo-db
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: admin
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: password
          - name: MONGO_INITDB_DATABASE
            value: admin
          - name: MONGODB_URI
            value: mongodb://mongo-db:27017
        ports:
        - containerPort: 27017
          name: mongo-db
        volumeMounts:
        - mountPath: /data/db
          name: mongo-db-data
      volumes:
      - name: mongo-db-data
        emptyDir: {}


---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-db
  name: mongo-db
spec:
  type: ClusterIP
  ports:
  - name: mongo-db
    port: 27017
    targetPort: mongo-db
  selector:
    app: mongo-db
