apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngo-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ngo-app
  template:
    metadata:
      labels:
        app: ngo-app
    spec:
    containers:
        - name: ngo-app-container
          image: 277285677846.dkr.ecr.eu-west-2.amazonaws.com/capstone:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: app-volume
              mountPath: /usr/src/app
          env:
            - name: DB_HOST
              value: mongo-db
            - name: DB_PORT
              value: "27017"
            - name: DB_USER
              value: admin
            - name: DB_PASS
              value: password
            - name: DB_NAME
              value: admin
  volumes:
        - name: app-volume
          hostPath:
            path: .
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: ngo-app
spec:
  selector:
    app: ngo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
        - name: mongo-db-container
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
            - name: MONGO_INITDB_DATABASE
              value: admin
            - name: MONGODB_URI
              value: mongodb://mongo-db:27017
      volumes:
        - name: mongo-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-db
spec:
  selector:
    app: mongo-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mongo-data
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: app-volume
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi